### ISSUE TITLE
Compilation issue - Fix little mistakes in csproj

### ISSUE THREAD

**Issue by IfZen** [korneliuscode/Superlist#1]
Hello!

There is a little mistake in BinaryComponents.SuperList.csproj: 

You must replace these two lines:
```
    <None Include="..\README.md" />
    <None Include="C:\Users\korne\Documents\GitHub\Superlist\README.md">
```
by this one (no "/>" at the end)
```
    <None Include="..\README.md" >
```

Thanks for providing us a repo for this Gui library.
I am using it for personnal tools after I read your codeproject article a decade ago.

**Comment by korneliuscode** [comment]
Thanks for the hint. I just fixed it with #a7f61bf.
